<a href="https://colab.research.google.com/github/Abhijeetlahane09/capstone_project-/blob/main/EDA_Airbnb_Project_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Name -  Airbnb NYC project
**Project Type** - EDA project (Exploratory Data Analyses)

**Contribution** - Individual

# Project Summary -


* **Project Objective:**


The primary objective of this project is to analyze and derive insights from a dataset containing Airbnb listings and booking information. By exploring this dataset, we aim to understand trends, patterns, and factors influencing property pricing and booking trends within a specific geographical area (e.g., a city or region).



*  **Dataset Information:**


1. **Data Source**: The dataset is sourced from Airbnb, a popular online platform

for booking accommodations. It includes historical data on listings, hosts,


reviews, and booking details.




2. **Data Size:** The dataset comprises [48,896] number of row's and [16] number of columns.

3. **Data Columns:** The dataset includes various columns, with key attributes **such as:**
        ['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365']



> **Required Information for Analysis:**
To accomplish our project objectives, we need to extract and analyze the following key information from the dataset:

1. **Property Characteristics:** Information about property types, sizes, amenities, and other features that influence pricing and booking trends.

2. **Pricing Data:** Historical pricing information for Airbnb listings, including daily, weekly, and monthly rates. This will be essential for pricing trend analysis.

3. **Availability and Occupancy:** Data on property availability, occupancy rates, and seasonal variations in booking rates.

4. **Host Information:** Insights into host characteristics, such as host ratings, response times, and the number of properties managed.

5. **Geospatial Data:** Latitude and longitude coordinates to visualize property locations on a map and analyze the geographical distribution of listings.

6. **Reviews and Ratings:** Review scores and comments from guests, which can provide insights into the quality of listings and factors influencing guest satisfaction.

7. **Booking Patterns:** Data on booking frequency, lead times, and the factors affecting booking decisions.

8. **Time Series Analysis:** Time series data to identify temporal trends in pricing and occupancy.

9. **Data Cleaning and Preprocessing:** Ensuring data quality by handling missing values, outliers, and data inconsistencies.

# GitHub Link - [link text](https://)

# Let's Begin !


>  Lets begin with importing required libriries for EDA

In [108]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb



> Lets get familiar with our dataset

In [109]:
# importing data form csv file uploaded on google drive
airbnb_df = pd.read_csv("/content/drive/MyDrive/practice files/Airbnb NYC 2019.csv")

In [110]:
# lets have a look at the data .
airbnb_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [111]:
# bottom view of the data
airbnb_df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [112]:
# view of all columns in airbnb df
airbnb_df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')



> **Here is the information about what this columns contains**

1. **id:** A unique identifier for each Airbnb listing.
2. **name:** The title or name of the listing as provided by the host.
3. **host_id:** A unique identifier for each host who lists properties on Airbnb.
4. **host_name:** The name of the host or property owner.
5. **neighbourhood_group:** The larger administrative division of New York City (e.g., Manhattan, Brooklyn)
6. **neighbourhood:** The specific neighborhood or area where the property is located.
7. **latitude:** Geographic latitude coordinates of the property.
8. **longitude:** Geographic longitude coordinates of the property.
9. **room_type:** The type of room or accommodation being offered (e.g., entire home/apartment, private room, shared room).
11. **price:** The nightly rental price for the listing.
12. **minimum_nights:** The minimum number of nights required for booking.
13. **number_of_reviews:** The total number of reviews for the listing.
14. **last_review:** The date of the last review left by a guest.
15. **reviews_per_month:** The average number of reviews received per month.
16. **calculated_host_listings_count:** The number of listings the host has on Airbnb, calculated from this property.
15. **availability_365:** The number of available nights for booking in the next 365 days.
These columns provide essential information about the Airbnb listings in New York City in 2019.

In [113]:
# lets have the additional info about not null values present in data and its data types.
airbnb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [114]:
# lets get the discription of data frame such as  count, measn, median, std, min , max and other.
airbnb_df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

# Data cleaning -



> **Handling missing values**
---

When data is missing from a dataset, it may be represented by other values such as '?' question marks, '-' dashes or blank spaces.

These values can create problems during data analysis as they cannot be recognized as missing data by most software packages and can interfere with calculations and statistics.

By converting these values to NaN (Not a Number), we can standardize the representation of missing data and make it easier to handle and process during data analysis.

In [115]:
# lets have a look at not null values in a column
# the total count of a non-null value should be 48895, if the colunt is less than 48895 it means that column contain null values
airbnb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB



> As we can see there is some missing values in columns :- ["name",
 "hoste_name",   "last_review",   "reviews_per_month"  .]

In [116]:
# the null values in a data frame is already represented by the Nan value
# lets finde how many null records present in a data.
airbnb_df.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64



*  **In the "name" and "host_name" column only few rows are missing and its not much  important for further analysis  so we can drop them**

In [117]:
# lets drop the null records from the name and host name column
airbnb_df.dropna(subset=["name","host_name"],axis= 0 , inplace = True)

In [118]:
# now you can see there is no null value in name and host_name column
airbnb_df.isna().sum()

id                                    0
name                                  0
host_id                               0
host_name                             0
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10037
reviews_per_month                 10037
calculated_host_listings_count        0
availability_365                      0
dtype: int64



* **we cant remove the missing values in last_review and reviews_per_month
columns, as they contain a huge data, removing them have a bad impact on analysis and we loss the important data.**
---

In [119]:
# so we decided to replace the null value of last_review as "Noreviews" and for review_per_month "0" as replacement
airbnb_df['last_review'].fillna('NoReviews', inplace=True)
airbnb_df['reviews_per_month'].fillna(0, inplace=True)

In [120]:
# as we can see now there is no null value present in data.
airbnb_df.isna().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [121]:
# now let's remove the duplicates
airbnb_df.drop_duplicates(inplace=True)

In [122]:
# Checking for duplicate rows
duplicate_rows = airbnb_df.duplicated()

# Filtering the DataFrame to show duplicate rows
duplicate_data = airbnb_df[duplicate_rows]
print(duplicate_data)
# there is no duplicate values present in our data

Empty DataFrame
Columns: [id, name, host_id, host_name, neighbourhood_group, neighbourhood, latitude, longitude, room_type, price, minimum_nights, number_of_reviews, last_review, reviews_per_month, calculated_host_listings_count, availability_365]
Index: []

# Data visualizations -